### ISSUE TITLE
MUC: How should a client determine the appropriate nickname to use when joining a MUC?

### ISSUE THREAD

**Issue by mwild1** [modernxmpp/modernxmpp#2]
Clients are proving to have a hard time choosing a consistent nickname. There are a variety of possible sources today, and clients seem to use a mixture of them, in various orders of priority:

- The nickname from MUC bookmarks
- PEP User Nickname
- vCard nickname
- A locally-configured alias
- The node part of the user's JID
- A nick chosen from a pre-join dialog (typically not shown for autojoin bookmarks)

**Comment by ge0rg** [comment]
Related issue: which nickname should a client show for a **contact**?

**Comment by mwild1** [comment]
@ge0rg that part (name for contact) was discussed at the Brussels UX sprint, documented here: https://docs.modernxmpp.org/client/design/#names

**Comment by mwild1** [comment]
Now documented at https://docs.modernxmpp.org/client/groupchat/#user-nickname
